# -*- coding: utf-8 -*-
"""MX_Bird_Parse

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fp95eiHevV5zsd60ykJEBoaljKpqIxHF
"""

import pandas as pd
import numpy as np
from PIL import Image
from io import BytesIO
from IPython.display import HTML
import os
from fastai.vision import *
from google.colab import drive
drive.mount('/content/drive')

# %cd /content/drive/My\ Drive/Datasets/MX_Birds_V2

df = pd.read_csv('/content/observations-152603.csv')
df = df.dropna(axis=0, subset=['image_url'])
df.head()

# os.chdir('/content/photos')

# !pwd

classes = list(df.common_name.unique())

#@title Creates a folder for each class
# classes = list(df.common_name.unique())
path = '/content/drive/My Drive/Datasets/MX_Birds_V2/'
for folder in classes:
    dest = path + str(folder)
    os.makedirs(dest)

list(os.listdir(path))

#@title Creates a .csv file in each subfolder for each class
for cla in classes:
  pathdl = path + str(cla)
  x = df.loc[df.common_name.astype(str) == str(cla)]
  x = x['image_url']
  x.to_csv(pathdl + "/" + str(cla), index=False)

#@title Downloads up to 200 images per class to its subdirectory
for cla in classes:
  try:
    path2 = '/content/drive/My Drive/Datasets/MX_Birds_V2/' + str(cla)
    print (cla)
    file = path2 + "/" + str(cla)
    dest = path2
    download_images(file, dest, max_pics=200)
  except:
    pass

for c in classes:
   print(c)
   verify_images(path + '/' + str(c), delete=True, max_size=500)

# import shutil
# path = '/content/drive/My Drive/Datasets/MX_Birds'
# for root, dirs, files in os.walk(path, topdown=False):
#   for dir in dirs:
#     if len(files) < 10:
#       shutil.rmtree(dir)